server {
    listen 80;
    server_name docs.projectdavid.co.uk;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name docs.projectdavid.co.uk;

    ssl_certificate     /etc/letsencrypt/live/docs.projectdavid.co.uk/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/docs.projectdavid.co.uk/privkey.pem;

    root  /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}